---
- name: make sure saml dependency packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - memcached
    - m2crypto
    - xmlsec1
    - swig

- name: add saml2 to production.ini plugins
  replace:
    dest: /etc/ckan/production.ini
    regexp: '^(ckan.plugins(?!.*\bsaml2\b).*)$'
    replace: '\1 saml2'

- name: get code
  git: repo={{item.repo}} dest={{ project_source_new_code_path }}/src/{{item.name}} version={{item.branch|default('master')}}
  with_items: "{{ saml2_pkgs }}"

- name: run setup
  command: chdir={{ project_source_new_code_path }}/src/{{item.name}}/ ../../bin/python setup.py develop
  with_items: "{{ saml2_pkgs }}"

- name: create directories
  action: file path=/etc/ckan/saml2/ state=directory mode=0755

- name: copy all needed files
  action: copy src=etc/ckan/saml2/{{saml2_idp_entry}}/ dest=/etc/ckan/saml2/

- name: copy template files
  template: src=templates/{{item}}.j2 dest=/{{item}}
  with_items:
    - etc/ckan/who.ini
