---
- name: create directories
  action: file path=/etc/ckan/saml2/ state=directory mode=0755 owner=root group=www-data

- name: create pki directory
  action: file path=/etc/ckan/saml2/pki state=directory mode=0750 owner=root group=www-data

- name: copy all needed files
  action: copy src=etc/ckan/saml2/ dest=/etc/ckan/saml2/ mode=0644 owner=root group=www-data
  notify: reload apache2

- name: template all needed files
  action: template src=etc/ckan/{{item}} dest=/etc/ckan/{{item}} mode=0640 owner=root group=www-data
  with_items:
    - saml2/pki/mycert.pem
    - saml2/pki/mykey.pem
    - who.ini
  notify: reload apache2

- name: Downloads idp metadata
  get_url:
    url: "{{ saml2_idp_metadata_url }}"
    dest: /etc/ckan/saml2/idp.xml
    mode: 0644
  notify: reload apache2
