- name: check if psql geo.gov role exists
  shell: psql -c "SELECT 1 FROM pg_roles WHERE rolname='ckan';"
  sudo: yes
  sudo_user: postgres
  register: check_ckan_db_user

- name: create geo.gov role
  when: check_ckan_db_user.stdout.find("(0 rows)") != -1
  shell: psql -c "CREATE USER ckan WITH PASSWORD 'pass' SUPERUSER;"
  sudo: yes
  sudo_user: postgres

- name: check if ckan database already exists
  shell: psql -c "SELECT 1 FROM pg_database WHERE datname = 'ckan';"
  sudo: yes
  sudo_user: postgres
  register: check_ckan_database

- name: create ckan database
  when: check_ckan_database.stdout.find("(0 rows)") != -1
  shell: psql -c "CREATE DATABASE ckan OWNER ckan;"
  sudo: yes
  sudo_user: postgres

- name: check if pycsw database already exists
  shell: psql -c "SELECT 1 FROM pg_database WHERE datname = 'pycsw';"
  sudo: yes
  sudo_user: postgres
  register: check_pycsw_database

- name: create pycsw database
  when: check_pycsw_database.stdout.find("(0 rows)") != -1
  shell: psql -c "CREATE DATABASE pycsw OWNER ckan;"
  sudo: yes
  sudo_user: postgres

- name: add postgis to pycsw database
  when: check_pycsw_database.stdout.find("(0 rows)") != -1
  shell: psql -d pycsw -c "CREATE EXTENSION postgis;"
  sudo: yes
  sudo_user: postgres

- name: install postgis script
  shell: "psql -d ckan -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql"
  sudo: yes
  sudo_user: postgres

- name: install postgis script
  shell: "psql -d ckan -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql"
  sudo: yes
  sudo_user: postgres

- name: install postgis script
  shell: "psql -d ckan -f /usr/share/postgresql/9.3/contrib/postgis-2.1/rtpostgis.sql"
  sudo: yes
  sudo_user: postgres

- name: install postgis script
  shell: "psql -d ckan -f /usr/share/postgresql/9.3/contrib/postgis-2.1/topology.sql"
  sudo: yes
  sudo_user: postgres

- name: install postgis script
  shell: psql -d ckan -c "GRANT SELECT, UPDATE, INSERT, DELETE ON spatial_ref_sys TO ckan;"
  sudo: yes
  sudo_user: postgres

- name: Initialize ckan db
  action: command ckan db init
