---
- name: reload apache2
  service: name=apache2 state=reloaded
  when: catalog_app_type == "web"

- name: reload supervisor
  command: supervisorctl reload
  when: catalog_app_type == "worker"
  tags:
    - skip_ansible_lint
