---

# WordPress env
#env_wp_env: development
env_wp_env: production
env_content_protocol: https

# wordpress app code
project_git_repo: https://github.com/GSA/datagov-wp-boilerplate.git
project_git_version: master

# Project path
project_source_rollback_path: /var/www/datagov/rollback
project_source_new_code_path: /var/www/datagov/new
current_source_symlink: /var/www/datagov/current
project_index_path: /var/www/datagov/current/web

# MySQL credentials
env_db_host: "{{ vault_env_db_host }}"
env_db_user: "{{ vault_env_db_user }}"
env_db_pass: "{{ vault_env_db_pass }}"
env_db_name: "{{ vault_env_db_name }}"

# s3
s3_bucket: bsp-ocsit-dev-east-appdata
s3_prefix: datagov/wordpress/

# SAML
saml_sp_cert: "{{ vault_saml_sp_cert }}"
saml_sp_key: "{{ vault_saml_sp_key }}"

saml_idp_id: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_sso: "https://{{ saml2_idp_entry }}/idp/profile/SAML2/POST/SSO"
saml_idp_slo: "https://{{ saml2_idp_entry }}/idp/profile/SAML2/POST/SLO"

# Generate your keys here: https://roots.io/salts.html
auth_key: "{{ vault_auth_key }}"
secure_auth_key: "{{ vault_secure_auth_key }}"
logged_in_key: "{{ vault_logged_in_key }}"
nonce_key: "{{ vault_nonce_key }}"
auth_salt: "{{ vault_auth_salt }}"
secure_auth_salt: "{{ vault_secure_auth_salt }}"
logged_in_salt: "{{ vault_logged_in_salt }}"
nonce_salt: "{{ vault_nonce_salt }}"

