---
- name: Update repositories cache and install tomcat6
  apt: name=tomcat6 update_cache=yes

- name: Download solr 4.2.1
  command: creates=~/solr-4.2.1.tgz chdir=~/ wget -T 40  {{ solr_url }}

- name: Unpack solr
  shell: "cd ~/ && tar -zxvf solr-4.2.1.tgz && cd solr-4.2.1/dist && cp solr-4.2.1.war /var/lib/tomcat6/webapps/solr.war"

- name: wait for the solr directory to be created
  wait_for: path=/var/lib/tomcat6/webapps/solr/WEB-INF/

- name: Create Solr home dir
  file: path=/home/solr state=directory

- name: Copy solr files to home dir
  shell: cp -R ~/solr-4.2.1/example/solr/* /home/solr

- name: remove old /home/solr/ckan if exists
  shell: rm -r /home/solr/ckan removes=/home/solr/ckan 

- name: move collection1 files to home dir
  shell: mv /home/solr/collection1 /home/solr/ckan creates=/home/solr/ckan

- name: Change default solr collection1 to ckan
  replace: dest=/home/solr/solr.xml regexp='collection1' replace='ckan'

- name: copy solr web.xml
  action: copy src={{item}} dest=/{{item}} mode=644 force=yes
  with_items:
    - var/lib/tomcat6/webapps/solr/WEB-INF/web.xml

- name: copy solr schema file
  action: copy src={{app_type}}/{{item}} dest=/{{item}} mode=644 force=yes
  with_items:
    - home/solr/ckan/conf/schema.xml

- name: Setup solr permissions
  shell: "chown -R tomcat6 /home/solr"

- name: restarting tomcat service
  action: service name=tomcat6 state=restarted
