---

# CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
codeigniter_environment: development
env_wp_env: development
real_ansible_env: local

default_email_from: "{{ vault_default_email_from }}"

# Nginx
nginx_remove_default_vhost: true
letsencrypt: false

# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "7A43DACB95D67FB6A804FD37C8A7DCA5B0384939"

# PHP-FPM
php_enable_php_fpm: true
php_fpm_listen: /var/run/php/php7.0-fpm.sock
php_webserver_daemon: nginx

# new python version
python_version_number: 2.7.10
python_version_name: Python-{{ python_version_number }}
python_version_url: https://www.python.org/ftp/python/{{ python_version_number}}/{{ python_version_name }}.tgz
python_version_directory: /usr/local/lib/python{{ python_version_number }}/
