--- # CRM prerequisites

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
  notify:
      - reload nginx

- name: Temporarily making /var/www/ writeable by all
  file:
    path: "/var/www"
    state: directory
    mode: 0777
    owner: "www-data"
    group: "www-data"
    recurse: yes

- name: MariaDB client
  package:
    name: mariadb-client-5.5
    state: present