---
td_agent:
  plugins:
    - { name: 'fluent-plugin-elasticsearch' }
    - { name: 'fluent-plugin-s3' }
  position_path: /var/log/td-agent/position
  aggregator:
    ipaddr: 10.0.0.71
    port: 24224

