---

- name: Gather VPC facts
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters: {
      "tag:Name":"{{ vpc_name }}",
      "tag:portofolio":"{{ portofolio }}" #, "tag:apps":"{{ apps }}"
    }
  register: vpc_facts

- name: Remove public route tables
  ec2_vpc_route_table:
    state: absent
    region: "{{ region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    tags: { 
      "Name":"{{ app }}-public-subnet-route-table"
    }

- name: Remove private route tables
  ec2_vpc_route_table:
    state: absent
    region: "{{ region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    tags: { 
      "Name":"{{ app }}-private-subnet-route-table"
    }
