---
- name: get code
  git:
    repo: "{{ item.repo }}"
    dest: "{{ virtualenv }}/src/{{ item.name }}"
    version: "{{ item.branch | default('master') }}"
    force: yes
  with_items: "{{ pkg }}"

- name: install requirements
  pip:
    requirements: "{{ virtualenv }}/src/{{ item.name }}/{{ item.requirements }}"
    virtualenv: "{{ virtualenv }}"
    virtualenv_python: "{{ python_home }}/bin/python"
  with_items: "{{ pkg }}"
  when: item.requirements is defined

- name: run setup
  command: chdir={{ virtualenv }}/src/{{ item.name }} {{ virtualenv }}/bin/python setup.py develop
  with_items: "{{ pkg }}"
  tags:
    - skip_ansible_lint
