---
- name: Install build dependencies
  apt: name={{ item }} state=present
  with_items:
    - memcached
    - swig
    - xmlsec1

- name: Create log directory
  file: path={{ inventory_log_dir }} state=directory owner=root group=www-data mode=0750

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Check whether new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: "mv {{ project_source_new_code_path }} {{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code
  file: path="{{ project_source_new_code_path }}" state=absent

- include: build-pkgs.yml
  vars:
    pkg: "{{ ckan_pkgs }}"
    virtualenv: "{{ project_source_new_code_path }}"

- name: Remove old datapusher code
  file: path="{{ datapusher_virtual_env }}" state=absent

- include: build-pkgs.yml
  vars:
    pkg: "{{ datapusher_pkgs }}"
    virtualenv: "{{ datapusher_virtual_env }}"

- name: create directories
  action: file path={{ item }} state=directory owner="www-data" group="www-data" mode=0755
  with_items:
    - /var/lib/ckan

- name: copy all needed files
  action: copy src={{ item }} dest=/{{ item }} owner=root group=www-data mode=0640
  with_items:
    - etc/ckan/who.ini
    - etc/ckan/apache.wsgi
    - etc/ckan/datapusher.wsgi

- name: Configure production.ini
  template: src={{ item }} dest=/{{ item }} owner=root group=www-data mode=0640
  with_items:
    - etc/ckan/production.ini
    - etc/ckan/datapusher_settings.py
    - etc/apache2/sites-enabled/ckan.conf
    - etc/apache2/sites-enabled/datapusher.conf


- include: additional-tasks.yml
  virtualenv: "{{ project_source_new_code_path }}"

- name: fix virtualenv permissions
  file: path={{ item }} state=directory group=www-data recurse=yes
  with_items:
    - "{{ datapusher_virtual_env }}"
    - "{{ project_source_new_code_path }}"

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ current_source_symlink }}"
    state: link

- name: restart apache
  action: service name=apache2 state=restarted
  tags:
    - molecule-notest

- name: point site_url in /etc/hosts to localhost
  action: lineinfile dest=/etc/hosts line="127.0.0.1 {{ ckan_site_domain | regex_replace('https?\://','') }}" state=absent
  tags:
    - molecule-notest # Device or resource busy ranaming temp file
