---

- name: Delete Web Proxy Auto Scaling Group
  ec2_asg:
    name: "{{ app }}_web_proxy_asg"
    state: absent
    region: "{{ region }}"
    launch_config_name: "{{ app }}-web-proxy-lc"
    wait_for_instances: True
    wait_timeout: 600
    tags:
      - app: "{{ app }}"
      - portofolio: "{{ vpc_name }}"
      - type: asg
