---

- name: Create ElastiCache Redis Service
  elasticache:
    name: "{{ app }}-redis"
    region: "{{ region }}"
    state: present
    engine: redis
    node_type: cache.m1.small
    num_nodes: 1
    cache_port: 6379
    cache_subnet_group: "{{ app }}-elasticache-subnet-group"
    security_group_ids: "{{ redis_sg.group_id }}"
    zone: "{{ subnets.private_subnet_1.az }}"
  register: elasticache_instance
