---

# Gather subnet facts
- name: Gather private subnet facts
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      { "tag:app": "{{ app }}", "tag:portofolio": "{{ vpc_name }}", "tag:type": "private" }
  register: private_subnets

- name: Extract the ids of the private subnets
  set_fact: private_subnet_ids={{ private_subnets.subnets | map(attribute='id') | list }}

- name: Add Elasticache subnet group
  elasticache_subnet_group:
    state: present
    region: "{{ region }}"
    name: "{{ app }}-elasticache-subnet-group"
    description: Elasticache Subnet Group
    subnets: "{{ private_subnet_ids }}"
  register:  elasticache_subnet_group
