---

- name: Create ElastiCache Redis Service
  elasticache:
    name: "{{ app }}-redis"
    region: "{{ region }}"
    state: present
    engine: redis
    node_type: cache.m1.small
    num_nodes: 1
    cache_port: 6379
#    cache_security_groups: "{{ app }}-redis-sg"
    zone: "{{ subnets.private_subnet_1.az }}"
  register: elasticache
