---

- name: Gather facts about route tables
  ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      { "tag:Name": "{{ app }}-private-subnet-route-table" } 
  register: route_table_facts

- name: Delete nat gateway and wait for deleted status
  ec2_vpc_nat_gateway:
    state: absent
    region: "{{ region }}"
#    release_eip: true
    nat_gateway_id: "{{ route_table_facts.route_tables[0].tags.nat_gateway_id }}"
    wait: yes
    wait_timeout: 600
  when: route_table_facts.route_tables|length > 0
