---

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ region }}"
    resource_tags: { "Name":"{{ app }}-public-subnet-route-table" }
    subnets: 
      - "{{ subnets.public_subnet_1.cidr }}"
      - "{{ subnets.public_subnet_2.cidr }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc.igw_id }}"
  register: public_route_table
