# Set Up Public subnets route tables

- name: Set up public subnet route table
  ec2_vpc_route_table:
    state: absent
    vpc_id: "{{ vpc.vpc_id }}"
    subnets: 
      - "{{ datagov_subnets.results[1].subnet.id }}"
      - "{{ datagov_subnets.results[2].subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
