---

# Create Public & Private Subnets in 2 AZs
- name: Create/Delete public/private subnets for "{{ app }}" app
  ec2_vpc_subnet:
    region: "{{ region }}"
    az: "{{ subnets[item]['az'] }}"
    state: "{{ state }}"
    vpc_id: "{{ vpc.vpc_id }}"
    cidr: "{{ subnets[item]['cidr'] }}"
    resource_tags: {"Name":"{{ app }}_{{ item }}_{{ subnets[item]['az'] }}" }
  register: datagov_subnets
  with_items: "{{ subnets }}"
