---
- name: get information on newest versions of packages and their dependencies
  apt: update_cache=yes

- name: make sure packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - htop
    - atool
    - ruby
    - python-virtualenv
    - python-setuptools
    - git
    - python-dev
    - ruby-dev
    - postgresql-client
    - bison
    - python-pip
    - libgeos-c1
    - libxml2-dev
    - libxslt1-dev
    - lib32z1-dev
    - libpq-dev
