---
- name: get information on newest versions of packages and their dependencies
  apt: update_cache=yes

- name: make sure packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - acl
    - htop
    - atool
    - ruby
    - python-virtualenv
    - python-setuptools
    - git
    - python-dev
    - ruby-dev
    - postgresql-client
    - bison
    - python-pip
    - libbz2-dev
    - libgeos-c1
    - libxml2-dev
    - libxslt1-dev
    - lib32z1-dev
    - libpq-dev
    - libffi-dev
    - libssl-dev
    - ntp

# Upgrade python to 2.7.10
- include: python-upgrade.yml

- name: install reboot-notify script
  copy: src=reboot-notify.sh dest=/usr/local/reboot-notify.sh mode=0755 owner=root group=root

  # In xenial+ a new package reboot-notifier does this
- name: notify when reboot is required
  cron: >-
    cron_file=reboot-notify
    special_time=daily
    state=present
    job=/usr/local/reboot-notify.sh

# The Network Time Protocol is used to manage the system clock over a network
# If every system on a network reliably reports the same time, then it is much easier to correlate log messages in case of an attack

- name: be sure ntp is installed
  apt: name=ntp state=installed
  tags:
    - ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
  tags:
    - ntp
    - AU-8

  # Prevent a bug in grub where update-grub hangs probing
  # devices
- name: ensure grub os prober is disabled
  lineinfile: >-
    path=/etc/default/grub
    line='GRUB_DISABLE_OS_PROBER=true'
    state=present
  tags:
    - skip_in_kitchen

- name: install GSA CA certificates
  copy: src=gsa.crt dest=/usr/local/share/ca-certificates/gsa.crt mode=0644 owner=root group=root
  register: gsa_ca_certificate

- name: update system certificates
  command: update-ca-certificates
  when: gsa_ca_certificate is changed
