---
- name: create ckan config dir
  action: file path=/etc/ckan state=directory owner=root group=www-data mode=0750 follow=yes

- name: copy executables
  action: copy src={{item}} dest=/{{item}} mode=0755 owner=root group=www-data
  with_items:
    - usr/bin/ckan

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/cron.daily/remove_old_sessions
  tags: ['cron']
