version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'password' > ~/ansible-secret.txt
      - run: pip install ansible
      - run: make update-vendor-force
      - run: make lint

  test:
    machine: true
    parallelism: 5
    steps:
      - checkout
      # Restore cache and install python dependencies
      - restore_cache:
          keys:
            - v1-pip-{{ checksum "requirements.txt" }}
            - v1-pip-
      - run: |
          virtualenv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - save_cache:
          key: v1-pip-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run: 
          name: Setup ansible-galaxy
          command: |
            . venv/bin/activate
            make update-vendor-force      
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            TEST_TARGETS=$(make circleci-glob | circleci tests split)
            make ${TEST_TARGETS}


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
