version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'password' > ~/ansible-secret.txt
      - run: pip install ansible
      - run: make update-vendor-force
      - run: make lint

  test:
    docker:
      - image: circleci/python:3.6
    parallelism: 5
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install pipenv
          command: pip install -U pipenv
      # Restore cache and install python dependencies
      - restore_cache:
          keys:
            - v3-pipenv-{{ checksum "Pipfile.lock" }}
            - v3-pipenv-
      - run:
          name: install python dependencies
          command: pipenv sync --dev
      - save_cache:
          key: v3-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run:
          name: Setup ansible-galaxy
          command: pipenv run make update-vendor-force
      - run:
          name: Run tests
          command: |
            TEST_TARGETS=$(make circleci-glob | circleci tests split)
            pipenv run make ${TEST_TARGETS}


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
