# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint

    working_directory: ~/repo

    steps:
      - run: ansible-lint --version
      - checkout
      - run:
          name: Generate fake vault password
          command: echo 'password' > ~/ansible-secret.txt

      # Ansible syntax check
      - run: ansible-playbook --syntax-check ansible/*.yml

      # Ansible lint check
      - run: ansible-lint -v -x ANSIBLE0010 --exclude=ansible/roles/vendor ansible/*.yml

  test-kitchen:
    machine: true
    steps:
      - checkout
      - run:
          name: Generate fake vault password
          command: echo 'password' > ansible-secret.txt
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test
          environment:
            KITCHEN_YAML: .kitchen.apache.yml

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test-kitchen:
          requires:
            - lint
