---
- name: Ensuring php_app_deployment_dir src directory exists
  file:
    path: "{{ php_app_deployment_dir }}/src"
    state: directory

- name: Copying index.php
  template:
    src: "index.php"
    dest: "{{ php_app_deployment_dir }}/src/index.php"

- name: Ensuring config directory exists
  file:
    path: "{{ php_app_deployment_dir }}/src/application/config/{{ web_app_env }}"
    state: directory

- name: Copying config files
  template:
    src: "{{ item }}"
    dest: "{{ php_app_deployment_dir }}/src/application/config/{{ web_app_env }}/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/*.php

- name: Ensuring simplesamlphp/config directory exists
  file:
    path: "{{ php_app_deployment_dir }}/src/vendor/simplesamlphp/simplesamlphp/config"
    state: directory

- name: Copying SAML config files
  template:
    src: "{{ item }}"
    dest: "{{ php_app_deployment_dir }}/src/vendor/simplesamlphp/simplesamlphp/config/{{ item | basename }}"
  with_fileglob:
    - ../templates/saml/config/*.php

- name: Ensuring simplesamlphp/metadata directory exists
  file:
    path: "{{ php_app_deployment_dir }}/src/vendor/simplesamlphp/simplesamlphp/metadata"
    state: directory

- name: Copying SAML metadata files
  template:
    src: "saml/metadata/{{ saml2_idp_entry }}/saml20-idp-remote.php"
    dest: "{{ php_app_deployment_dir }}/src/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php"
