---
# CRM prerequisites

- name: Installing required packages
  package:
    name:
      - mariadb-client
      - php-zip
      - nginx-extras
    state: present

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/default.conf"
  notify:
    - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Copy SAML crt
  template:
    src: "mycert.pem"
    dest: "{{ saml_sp_cert_path }}"
    mode: 0644

- name: Copy SAML key
  template:
    src: "mykey.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644
