---
# CRM prerequisites

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
  notify:
    - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Copy SAML crt
  template:
    src: "mycert.pem"
    dest: "{{ saml_sp_cert_path }}"
    mode: 0644

- name: Copy SAML key
  template:
    src: "mykey.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: Installing required trusty packages
  apt:
    name:
      - mariadb-client-5.5
      - mariadb-client
      - php-zip
      - nginx-extras
    state: present
    force: yes
  when: ansible_distribution_release == "trusty"

- name: Installing required bionic packages
  apt:
    name:
      - mariadb-client-10.1
      - mariadb-client
      - php-zip
      - nginx-extras
    state: present
    force: yes
  when: ansible_distribution_release == "bionic"

- name: Import nginx extra modules
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'include /etc/nginx/modules-enabled/*.conf;'
    create: yes
    insertbefore: BOF
