---
ckan_session_store_type: ext:database

# server readonly/writable type
readwrite_type: writable

# db credentials
ckan_db_server: "{{ vault_ckan_db_server }}"
catalog_db_user: "{{ vault_catalog_db_user }}"
catalog_db_pass: "{{ vault_catalog_db_pass }}"
catalog_db_name: "{{ vault_catalog_db_name }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"

catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"


# other
catalog_ckan_solr_host: datagov-solrm1d.dev-ocsit.bsp.gsa.gov
