--- # CRM prerequisites

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
  notify:
      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Copy SAML crt
  copy:
    src: "{{ saml2_idp_entry }}/mycert.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: Copy SAML key
  copy:
    src: "{{ saml2_idp_entry }}/mykey.pem"
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: MariaDB client
  package:
    name: mariadb-client-5.5
    state: present

- name: PHP mcrypt
  package:
    name: php-mcrypt
    state: present