--- # CRM prerequisites

- name: Copying CRM configuration for Nginx
  template:
    src: "crm.nginx.conf"
    dest: "/etc/nginx/sites-enabled/crm.nginx.conf"
  notify:
      - reload nginx

- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"

- name: Copying SAML crt
  template:
    src: crm-saml-sp-cert.crt
    dest: "{{ saml_sp_cert_path }}"
    mode: 0644

- name: Copying SAML pem
  template:
    src: crm-saml-sp-private.pem
    dest: "{{ saml_sp_private_key_path }}"
    mode: 0644

- name: MariaDB client
  package:
    name: mariadb-client-5.5
    state: present

- name: PHP mcrypt
  package:
    name: php-mcrypt
    state: present