--- # Environment init

- name: Ensure https support for apt is installed
  apt:
    name: apt-transport-https
    state: present

- name: Add repository for PHP
  apt_repository:
    repo: "ppa:ondrej/php"
  register: ppa

- name: Update Apt
  apt: update_cache=yes
  when: ppa is changed

- name: Installing unzip (required by composer)
  apt:
    name: unzip
    state: present

- name: Cron hourly php7.x-fpm reload
  copy:
    src: php7reload
    dest: /etc/cron.hourly/php7reload
    mode: 0700
