---

- hosts: all
  tasks:
   - name: Remove the Treasuredata apt repository
     apt_repository:
       repo: 'deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib'
       state: absent

   - name: Uninstall and purge fluentd
     apt:
       name: td_agent
       purge: yes
       state: absent

   - name: Remove useless packages from the cache
     apt:
       autoclean: yes
       autoremove: yes

   - name: Delete td-agent rubygems
     file:
       path: /opt/td-agent
       state: absent

   - name: Delete td-agent config
     file:
       path: /etc/td-agent
       state: absent

   - name: Delete td-agent logs
     file:
       path: /var/log/td-agent
       state: absent