---
- include: fgdc2iso.yml
  tags: ['fgdc2iso']

- include: redis.yml
  tags: ['redis']

- name: install supervisor
  action: pip name=supervisor virtualenv=/usr/lib/ckan/

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/supervisord.conf
    - etc/init/supervisor.conf

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/cron.d/ckan
    - etc/cron.d/supervisor
  tags: ['cron']

- name: create superviserctl symlink
  action: file src=/usr/lib/ckan/bin/supervisorctl dest=/usr/bin/supervisorctl state=link

- name: start supervisor
  service: name=supervisor state=started
