---
- name: prepare packages needed for harvester
  action: apt pkg={{item}} state=installed
  with_items:
  - redis-server

- name: copy redis.conf
  copy: src=etc/redis/redis.conf dest=/etc/redis/redis.conf
  # need to check changes and restart redis if necessary
  register: restartredis

- name: restart redis
  service: name=redis-server state=restarted
  when: restartredis.changed 
