---
- name: get environment vars
  command: ls

- name: get environment vars
  set_fact:
    ckan_db_server: "{{ lookup('env', 'CKAN_DB_SERVER') }}"
    redis_server: "{{ lookup('env','REDIS_SERVER') }}"
    solr_server: "{{ lookup('env','SOLR_SERVER') }}"
    pycsw_db_server: "{{ lookup('env','PYCSW_DB_SERVER') }}"

- name: Config db_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*db_server\s*=).*$' replace='\1 {{ckan_db_server}}'
  when: ckan_db_server != ""

- name: Config redis_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*ckan\.harvest\.mq\.hostname\s*=).*$' replace='\1 {{redis_server}}'
  when: redis_server != ""

- name: Config solr_server in production.ini
  replace: dest=/etc/ckan/production.ini regexp='(\s*solr_server\s*=).*$' replace='\1 {{solr_server}}'
  when: solr_server != ""

- name: Config pycsw_db_server in pycsw config files
  replace: dest={{ items }} regexp='(\s*db_server\s*=).*$' replace='\1 {{pycsw_db_server}}'
  when: pycsw_db_server != ""
  with_items:
    - /etc/ckan/pycsw-all.cfg
    - /etc/ckan/pycsw-collection.cfg
