---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  - name: catalog-ckan-app-trusty
    image: ubuntu:trusty
    # start-stop-daemon doesn't detect tomcat is running in docker and `service
    # start/stop` fails. SYS_PTRACE is needed.
    # https://stackoverflow.com/questions/29683231/tomcat7-fail-to-start-inside-ubuntu-docker-container/29686963#29686963
    capabilities:
      - SYS_PTRACE
  - name: catalog-ckan-app-bionic
    image: ubuntu:bionic
    # start-stop-daemon doesn't detect tomcat is running in docker and `service
    # start/stop` fails. SYS_PTRACE is needed.
    # https://stackoverflow.com/questions/29683231/tomcat7-fail-to-start-inside-ubuntu-docker-container/29686963#29686963
    capabilities:
      - SYS_PTRACE
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  # Disable idempotence check
  # davidwittman.redis is not idempotent
  # https://github.com/DavidWittman/ansible-redis/pull/202
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
