--- # Rolling back Data.gov deployment

- name: Load inventory specific vault ({{ vars_group }})
  include_vars: "group_vars/{{ vars_group }}/vault.yml"
  ignore_errors: yes

- name: Load inventory specific variables ({{ vars_group }})
  include_vars: "group_vars/{{ vars_group }}/vars.yml"
  ignore_errors: yes

- name: Check weather rollback code dir exists
  stat: path="{{ project_source_rollback_path }}"
  register: p

- name: Check weather new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p2

- name: Symlink current dir with rollback dir
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ project_source_path }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code dir
  file: path="{{ project_source_new_code_path }}" state=absent
  when: p.stat.isdir is defined and p.stat.isdir

- name: Create new code
  command: cp -r "{{ project_source_rollback_path }}" "{{ project_source_new_code_path }}"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Symlink current dir with new dir
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ project_source_path }}"
    state: link
  when: p2.stat.isdir is defined and p2.stat.isdir

- name: Remove rollback code
  file: path="{{ project_source_rollback_path }}" state=absent
  when: p2.stat.isdir is defined and p2.stat.isdir
