---

- name: Create Web Proxy Auto Scaling Group
  ec2_asg:
    name: "{{ app }}_web_proxy_asg"
    region: "{{ region }}"
    load_balancers: "{{ external_elb.elb.name }}"
    launch_config_name: "{{ app }}-web-proxy-lc"
    min_size: "{{ web_proxy.min_size }}"
    max_size: "{{ web_proxy.max_size }}"
    vpc_zone_identifier: "{{ public_subnet_ids }}"
    health_check_period: "{{ web_proxy.health_check_period }}"
    health_check_type: "{{ web_proxy.health_check_type }}"
    tags:
      - Name: "{{ app }}_web_proxy"
      - app: "{{ app }}"
      - portofolio: "{{ vpc_name }}"
      - type: asg
      - service: web_proxy

- name: Create Web Auto Scaling Group
  ec2_asg:
    name: "{{ app }}_web_asg"
    region: "{{ region }}"
    load_balancers: "{{ internal_elb.elb.name }}"
    launch_config_name: "{{ app }}-web-lc"
    min_size: "{{ web.min_size }}"
    max_size: "{{ web.max_size }}"
    vpc_zone_identifier: "{{ private_subnet_ids }}"
    health_check_period: "{{ web.health_check_period }}"
    health_check_type: "{{ web.health_check_type }}"
    wait_for_instances: True
    wait_timeout: 600
    tags:
      - Name: "{{ app }}_web"
      - app: "{{ app }}"
      - portofolio: "{{ vpc_name }}"
      - type: asg
      - service: web

- name: Create Jump Box Auto Scaling Group
  ec2_asg:
    name: "{{ app }}_jump_box_asg"
    region: "{{ region }}"
    launch_config_name: "{{ app }}-jump-box-lc"
    min_size: "{{ jump_box.min_size }}"
    max_size: "{{ jump_box.max_size }}"
    vpc_zone_identifier: "{{ public_subnet_ids }}"
    health_check_period: "{{ jump_box.health_check_period }}"
    health_check_type: "{{ jump_box.health_check_type }}"
    tags:
      - Name: "{{ app }}_jump_box"
      - app: "{{ app }}"
      - portofolio: "{{ vpc_name }}"
      - type: asg
      - service: jump_box
