---

- name: Delete Web Proxy Launch Configuration
  ec2_lc:
    name: "{{ app }}-web-proxy-lc"
    image_id: "{{ web_proxy_ami_id }}"
    region: "{{ region }}"
    state: absent

- name: Delete Web Launch Configuration
  ec2_lc:
    name: "{{ app }}-web-lc"
    image_id: "{{ web_ami_id }}"
    region: "{{ region }}"
    state: absent

- name: Delete Jump Box Launch Configuration
  ec2_lc:
    name: "{{ app }}-jump-box-lc"
    region: "{{ region }}"
    state: absent
