---

- name: Create multi-zone Postgres instance for Wordpress on RDS
  rds:
    command: create
    instance_name: "{{ wordpress_db_instance_name }}"
    region: "{{ region }}"
    db_engine: "{{ db_engine }}"
    engine_version: "{{ engine_version }}"
    instance_type: "{{ db_instance_type }}"
    multi_zone: "{{ db_multi_zone}}"
    publicly_accessible: "{{ db_publicly_accessible }}"
    size: "{{ wordpress_db_size }}"
    maint_window: "{{ db_maint_window }}"
    backup_retention: "{{ db_backup_retention }}"
    backup_window: "{{ db_backup_window }}"
    license_model: "{{ db_license_model }}"
    subnet: "{{ app }}-rds-subnet-group" 
    vpc_security_groups: "{{ db_sg.group_id }}"
    wait: yes
    wait_timeout: 1200  
    db_name: "{{ env_db_name }}"
    username: "{{ env_db_user }}"
    password: "{{ env_db_pass }}"
    tags:
      app: "{{ app }}"
      portofolio: "{{ vpc_name }}"
      type: db
  register: wordpress_rds
