---

# RDS SG
- name: Delete db security group
  ec2_group:
    description: db security group
    region: "{{ region }}"
    name: "{{ app }}-db-sg"
    state: absent

# Web SG
- name: Delete Web ec2 security group
  ec2_group:
    description: web security group
    region: "{{ region }}"
    name: "{{ app }}-web-sg"
    state: absent

#Internal ELB SG
- name: Delete Internal ELB security group
  ec2_group:
    description: Internal ELB security group
    name: "{{ app }}-internal-elb-sg"
    region: "{{ region }}"
    state: absent

# Web Proxy SG
- name: Delete WebProxy security group
  ec2_group:
    description: WebProxy security group
    region: "{{ region }}"
    name: "{{ app }}-web-proxy-sg"
    state: absent

#Jump Host SG
- name: Delete Jump Host security group
  ec2_group:
    description: Jump Host security group
    name: "{{ app }}-jump-host-sg"
    region: "{{ region }}"
    state: absent

#External ELB SG
- name: Delete External ELB security group
  ec2_group:
    description: External ELB security group
    name: "{{ app }}-external-elb-sg"
    region: "{{ region }}"
    state: absent
