--- # Install the trendmicro agent

- name: get agent.rpm
  get_url:
    url: https://dsm.sec.helix.gsa.gov:443/software/agent/Ubuntu_14.04/x86_64/
    dest: /tmp/agent.deb
    validate_certs: no

- name: install trendmicro rpm
  shell: dpkg -i /tmp/agent.deb

- name: sleep 10 seconds
  shell: sleep 10

- name: start trendmicro agent @ web tier
  shell: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id_web }}"
  when: |
    (inventory_hostname in groups["catalog-web"]) or 
    (inventory_hostname in groups["inventory-web"]) or
    (inventory_hostname in groups["crm-web"]) or
    (inventory_hostname in groups["dashboard-web"]) or
    (inventory_hostname in groups["wordpress-web"]) or
    (inventory_hostname in groups["jekyll-web"])

- name: start trendmicro agent @ app tier
  shell: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id_app }}"
  when: | 
    (inventory_hostname in groups["solr"]) or 
    (inventory_hostname in groups["catalog-harvester"])

- name: start trendmicro agent @ mgmt web tier
  shell: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id_mgmt_web }}"
  when: ("efk_nginx" in groups) and (inventory_hostname in groups["efk_nginx"])

- name: start trendmicro agent @ mgmt app tier
  shell: /opt/ds_agent/dsa_control -a dsm://dsm.sec.helix.gsa.gov:4120/ "policyid:{{ trendmicro_policy_id_mgmt_app }}"
  when: | 
    (("kibana" in groups) and (inventory_hostname in groups["kibana"])) or
    (("elasticsearch" in groups) and (inventory_hostname in groups["elasticsearch"]))
