---
- name: default apache removed
  action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: wsgi config
  action: copy src=apache.wsgi dest=/etc/ckan/apache.wsgi

- name: ckan apache config
  action: copy src=ckan.conf dest=/etc/apache2/sites-enabled/ckan.conf

- name: Apache | Enable some required modules
  action: command a2enmod rewrite headers 
  tags: common

- name: restart apache
  action: service name=apache2 state=restarted
