---
- name: install jumpbox packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    # These are mostly dependencies for datagov-deploy's requirements.txt
    - git
    - openssh-server

- name: install global pipenv for managing ansible dependencies
  pip: name=pipenv executable=/usr/local/pyenv/versions/3.6.8/bin/pip virtualenv_python=/usr/local/pyenv/versions/3.6.8/bin/python state=present

- name: Create/remove the user account
  user:
    name: "{{ item.username }}"
    comment: "{{ item.email }}"
    shell: /bin/bash
    state: "{{ item.removed is defined and 'absent' or 'present' }}"
    password_lock: yes
    expires: -1
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH public key directory structure
  file: >-
    path=/home/{{ item.username }}/.ssh
    state=directory
    mode=0700
    owner={{ item.username }}
    group={{ item.username }}
  when: item.removed is undefined
  with_items: "{{ jumpbox_operators }}"

- name: Copy SSH public key
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    exclusive: True
    state: "present"
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Update the system /etc/sudoers file
  template: >-
    src=sudoers.j2
    dest=/etc/sudoers.d/{{ item.username }}
    mode=0600
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Remove sudoers for removed users
  file: >-
    dest=/etc/sudoers.d/{{ item.username }}
    state=absent
  when: item.removed is defined
  with_items: "{{ jumpbox_operators }}"
