---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ci
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../../../roles/vendor/
  inventory:
    group_vars:
      all:
        ci_inventory: inventories/example
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
