---

# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"
solr_master_server: "{{ vault_solr_master_server }}"

# TrendMicro
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# Nginx
nginx_remove_default_vhost: true
letsencrypt: false

# CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
codeigniter_environment: production
env_wp_env: production
real_ansible_env: staging

# postfix
postfix_relayhost: smtp.gsa.gov 
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_relaytls: true
default_email_from: "{{ vault_default_email_from }}"

#FluentD
fluentd_aws_access_key_id: "{{ vault_fluentd_aws_access_key_id }}"
fluentd_aws_secret_access_key: "{{ vault_fluentd_aws_secret_access_key }}"

# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "7A43DACB95D67FB6A804FD37C8A7DCA5B0384939"

# PHP-FPM
php_enable_php_fpm: true
php_fpm_listen: /var/run/php/php7.0-fpm.sock
php_webserver_daemon: nginx
