# TrendMicro
trendmicro_policy_id_mgmt_app: "{{ vault_trendmicro_policy_id_mgmt_app }}"
trendmicro_policy_id_mgmt_web: "{{ vault_trendmicro_policy_id_mgmt_web }}"

# Elasticsearch/Kibana shared creds
kibana_elasticsearch_username: "{{ vault_kibana_elasticsearch_username }}"
kibana_elasticsearch_password: "{{ vault_kibana_elasticsearch_password }}"
elasticsearch_port: 9200
kibana_port: 5601