# TrendMicro
trendmicro_policy_id_mgmt_app: "{{ vault_trendmicro_policy_id_mgmt_app }}"
trendmicro_policy_id_mgmt_web: "{{ vault_trendmicro_policy_id_mgmt_web }}"

#elastalert
elastalert_version: v0.1.8
slack_webhook_url: "{{ vault_slack_webhook_url }}" 
