---
virtual_env: /usr/lib/ckan
catalog_db_name: ckan_db

##################################
# Secret vars section
##################################
catalog_db_user: "{{ vault_catalog_db_user }}"
catalog_db_pass: "{{ vault_catalog_db_pass }}"
