---
virtual_env: /usr/lib/ckan
catalog_db_name: ckan_db
catalog_pycsw_db_name: pycsw_db
inventory_db_name: ckan_db
inventory_datastore_name: datastore_db

##################################
# Secret vars section
##################################
catalog_db_user: "{{ vault_catalog_db_user }}"
catalog_db_pass: "{{ vault_catalog_db_pass }}"
inventory_db_user: "{{ vault_inventory_db_user }}"
inventory_db_pass: "{{ vault_inventory_db_pass }}"
inventory_datastore_user: "{{ vault_inventory_datastore_user }}"
inventory_datastore_pass: "{{ vault_inventory_datastore_pass }}"
inventory_datastore_ro_user: "{{ vault_inventory_datastore_ro_user }}"
inventory_datastore_ro_pass: "{{ vault_inventory_datastore_ro_pass }}"

aws_access_key_for_s3: "{{ vault_aws_access_key_for_s3 }}"
aws_secret_key_for_s3: "{{ vault_aws_secret_key_for_s3 }}"
