---
- name: Provision Catalog databases
  hosts: catalog-web
  roles:
    - role: gsa.datagov-deploy-postgresql
      vars:
        postgresql_app_name: catalog
        postgresql_role_password: "{{ catalog_ckan_db_pass }}"
      tags:
        - database
      when: datagov_enable_postgresql_role is defined
    - role: gsa.datagov-deploy-postgresql
      vars:
        postgresql_app_name: pycsw
        postgresql_role_password: "{{ catalog_pycsw_db_pass }}"
      tags:
        - database
      when: datagov_enable_postgresql_role is defined



- name: Catalog web stack
  hosts: catalog-web
  serial: 1
  vars:
      app_type: catalog

  roles:
    - role: software/common/tls
      tags:
        - tls

    - role: software/ckan/common

    - role: gsa.datagov-deploy-apache2
      tags:
        - apache

    - role: software/ckan/catalog/ckan-app
      vars:
        app_repo_branch: "{{ catalog_ckan_app_version }}"
      tags:
        - app-deploy

    - role: software/ckan/catalog/www
      tags:
        - apache2

    - role: software/ckan/catalog/pycsw-app
      tags:
        - pycsw

    - role: software/ckan/saml2
      tags:
        - saml2

    - role: software/ckan/fix-ckan-tracking
      tags:
        - frontend
