---
- name: Install CKAN Stack
  hosts: catalog-web:catalog-harvester
  serial: 1
  vars:
      app_type: catalog

  ## tags used:
  ## built-in: always
  ## frontend, harvester, db, db-install, db-setup, db-init, solr, pycsw
  ## redis, fgdc2iso, cron
  ## sample usage: ansible-playbook ansibe/catalog.yml --tags "harvester" --skip-tags "solr,apache"
  roles:
    - {role: software/common/tls, tags: [frontend, tls]}
    - {role: software/ckan/common, tags: ['frontend', 'harvester']}
    - {role: gsa.datagov-deploy-apache2, tags: ['frontend', 'apache']}
    - {role: software/ckan/postgresql, tags: ['frontend', 'harvester', 'db', 'db-install']}
    - role: gsa.datagov-deploy-postgresql
      tags: ['frontend', 'db']
      when: datagov_enable_postgresql_role is defined
    - {role: software/ckan/solr, tags: ['frontend', 'harvester', 'solr']}
    - {role: software/catalog/ckan-app, tags: ['frontend', 'harvester', 'deploy']}
    - {role: software/catalog/ckan-db-setup, tags: ['frontend', 'harvester', 'db', 'db-setup']}
    - {role: software/catalog/ckan-db-init, tags: ['frontend', 'harvester', 'db', 'db-init']}

    - {role: software/catalog/harvest, tags: ['harvester']}

    - {role: software/catalog/pycsw-app, tags: ['frontend', 'harvester', 'pycsw']}
    - {role: software/catalog/pycsw-db-setup, tags: ['frontend', 'harvester', 'pycsw','db', 'db-setup']}
    - {role: software/catalog/pycsw-db-init, tags: ['frontend', 'harvester', 'pycsw','db', 'db-init']}

    - {role: software/ckan/saml2, tags: ['frontend', 'harvester', 'saml2']}

    - {role: software/ckan/security-fix, tags: ['frontend', 'harvester', 'pycsw']}

    - {role: software/ckan/fix-ckan-tracking, tags: ['frontend']}

    - {role: software/common/datagov-deploy-rollback, tags: ['deploy-rollback']}
