---
- name: Install CKAN Stack
  hosts: ckan-server
  sudo: yes
  #remote_user: ubuntu

  roles:
    - roles/software/ckan/common
    - roles/software/catalog/apache
    - roles/software/catalog/postgresql
    - roles/software/catalog/solr
    - roles/software/catalog/ckan-app
    - roles/software/catalog/ckan-db
    - roles/software/catalog/ckan-harvest
    - roles/software/catalog/pycsw
    - roles/software/catalog/saml2
