---

- name: Setup CI
  hosts: jumpbox
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - {role: gsa.datagov-deploy-ci, tags: [ci]}
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: ci
          path: /var/log/ci.log
          options:
            - daily
            - rotate 7
