---

- name: Setup CI
  hosts: vagrant
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - role: ci
    - role: logrotate
      logrotate_scripts:
        - name: ci
          path: /var/log/ci.log
          options:
            - daily
            - rotate 7
