---
- import_playbook: common/ubuntu.yml
- import_playbook: common/secops.yml
- import_playbook: common/trendmicro.yml
- import_playbook: common/fluentd.yml
  when: fluentd_disable is undefined
- import_playbook: common/misc.yml
- import_playbook: common/postfix.yml
