--- # crm Web AMI

#- name: Initial prechecks
#  hosts: crm-web
#  remote_user: ubuntu
#
#  roles:
#  - { role: crm-sudo-0-precheck, tags: [precheck] }

- name: Provisioning Web AMI
  hosts: crm-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - die-no-tags
  - { role: misc, tags: [provision, misc] }
  - { role: php-common, tags: [provision] }
  - { role: git, tags: [provision] }
  - { role: nginx, tags: [provision] }
  - { role: php, tags: [php, provision] }
  - { role: php-mysql, tags: [php, php-mysql, provision] }
  - { role: php-memcached, tags: [php, php-memcached, provision] }
  - { role: composer, tags: [php, provision] }
  - { role: vim, tags: [provision, vim] }
  - { role: crm-sudo-2-init, tags: [provision, deploy, deploy-rollback] }
  - { role: secops-ssh, tags: [provision, secops, prod] }
  - { role: trendmicro, tags: [provision, trendmicro, prod] }
  - { role: ansible-postfix, tags: [provision, postfix, prod] }
  - {role: roles/monitoring/fluentd/kernel, tags: [frontend, harvester, fluentd, prod] }
  - {role: roles/monitoring/fluentd/limits, tags: [frontend, harvester, fluentd, prod] }
  - {role: roles/monitoring/fluentd/td-agent, tags: [frontend, harvester, fluentd, prod] }


- name: Deploying crm
  hosts: crm-web
  remote_user: ubuntu

  roles:
  - { role: crm-deploy, tags: [provision, deploy] }
  - { role: datagov-deploy-rollback, tags: [deploy-rollback] }


- name: Cleanup
  hosts: crm-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - { role: php-fixes, tags: [php, provision, deploy] }
  - { role: crm-sudo-3-cleanup, tags: [provision, deploy, asdf, deploy-rollback] }

- name: CRM Migration
  hosts: crm-web
  remote_user: ubuntu

  roles:
  - { role: crm-migrations, tags: [provision, deploy, migrate] }
