---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/infrastructure/common/vars/main.yml
    - roles/infrastructure/catalog/vars/main.yml

  tasks:
    - include: roles/infrastructure/catalog/tasks/delete_sg.yml
    - include: roles/infrastructure/catalog/tasks/delete_route_tables.yml
    - include: roles/infrastructure/catalog/tasks/delete_subnets.yml
    - include: roles/infrastructure/common/tasks/delete_igw.yml
    - include: roles/infrastructure/common/tasks/delete_vpc.yml
