---

- name: Install ElasticSearch
  hosts: elasticsearch
  serial: 1
  roles:
  - ANXS.apt
  - geerlingguy.java
  - geerlingguy.elasticsearch

- name: Install Kibana
  hosts: kibana
  serial: 1
  roles:
  - geerlingguy.kibana

- name: Install EFK nginx proxy
  hosts: efk_nginx
  serial: 1
  roles:
  - role: geerlingguy.nginx
  - role: monitoring/efk-nginx

- name: Install Elastalert
  hosts: elasticsearch
  serial: 1
  roles:
    - role: ANXS.build-essential
    - role: gsa.elastalert
    - role: monitoring/elastalert
