---
- name: Install Elastalert
  hosts: elasticsearch
  become: yes
  become_method: sudo
  remote_user: ubuntu

  roles:
    - { role: ANXS.build-essential }
    - { role: gsa.elastalert }
    - { role: monitoring/elastalert }
