---
- name: Provisioning Inventory CKAN Stack 
  hosts: all
  serial: 1
  vars:
    app_type: inventory

  roles:
    - {role: software/common/tls, tags: ['tls']}
    - software/ckan/common
    - {role: gsa.datagov-deploy-apache2, tags: ['apache']}
    - {role: software/ckan/postgresql, tags: ['db', 'db-install']}
    - {role: software/ckan/solr, tags: ['solr']}
    - {role: software/inventory/ckan-app, tags: ['deploy']}
    - {role: software/ckan/saml2, tags: ['saml2']}
    - software/ckan/security-fix
    - {role: software/inventory/ckan-db-setup, tags: ['db', 'db-setup']}
    - {role: software/inventory/ckan-db-init, tags: ['db', 'db-init']}
    - {role: software/common/datagov-deploy-rollback, tags: ['deploy-rollback']}
