---
- name: Install Jekyll Apps
  hosts: jekyll-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  vars:
    ruby_version: "2.3.0"
    gemset: "jekyll"
    jekyll_apps:
      - {
          name: "sdg-indicators",
          repo: "https://github.com/GSA/sdg-indicators/",
          config: "_config_prod.yml",
          branch: "master",
          port: 8000,
          s3_bucket: "{{ s3_bucket_sdg | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }
      - {
          name: "data-federation",
          repo: "https://github.com/GSA/us-data-federation",
          config: "_config_prod.yml",
          branch: "master",
          port: 8001,
          s3_bucket: "{{ s3_bucket_federation | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }
      - {
          name: "data-strategy",
          repo: "https://github.com/GSA/data-strategy",
          config: "_config_prod.yml",
          branch: "master",
          port: 8002,
          s3_bucket: "{{ s3_bucket_strategy | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }

  roles:
    - software/ubuntu/common
    - {role: software/common/secops-ssh, tags: ['secops'] }
    - {role: software/common/trendmicro, tags: ['trendmicro'] }
    - {role: monitoring/fluentd/kernel, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/limits, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/td-agent, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: software/common/misc, tags: ['misc'] }
<<<<<<< HEAD
<<<<<<< HEAD
    - software/ckan/apache
    - software/jekyll
=======
    - role: gsa.datagov-deploy-apache2
>>>>>>> ad406c5054b42d2aa2b78bb7102aa7eea2af4592
=======
    - software/jekyll
    - role: gsa.datagov-deploy-apache2
>>>>>>> 76429afcd52034d06482def455fe5469de1b996a
    - { role: gsa.rvm1-ruby,
        rvm1_rvm_check_for_updates: False,
        rvm1_rubies: ['ruby-{{ruby_version}}'],
      }

