---
- name: Install Jekyll Apps
  hosts: jekyll-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  vars:
    ruby_version: "2.3.0"
    gemset: "jekyll"
    jekyll_apps:
      - {
          name: "sdg-indicators",
          repo: "https://github.com/GSA/sdg-indicators/",
          config: "_config_prod.yml",
          branch: "master",
          port: 8000,
          s3_bucket: "{{ s3_bucket_sdg }}",
          secret_key: "{{ jekyll_webhook_secret }}"
        }
      - {
          name: "data-federation",
          repo: "https://github.com/GSA/us-data-federation",
          config: "_config_prod.yml",
          branch: "master",
          port: 8001,
          s3_bucket: "{{ s3_bucket_federation }}",
          secret_key: "{{ jekyll_webhook_secret }}"
        }

  roles:
    - roles/software/ubuntu/common
    - {role: secops-ssh, tags: [secops] }
    - roles/software/ckan/apache
    - { role: rvm1-ruby,
        rvm1_rvm_check_for_updates: False,
        rvm1_rubies: ['ruby-{{ruby_version}}'],
      }
    - roles/software/jekyll

