---
- name: Install Jekyll Apps
  hosts: jekyll-web
  serial: 1
  vars:
    ruby_version: "2.3.8"
    gemset: "jekyll"
  roles:
    - {role: software/common/tls, tags: ['tls']}
    - {role: gsa.datagov-deploy-apache2, tags: ['apache']}
    - role: rvm.ruby
      rvm1_user: root
      rvm1_install_path: /usr/local/rvm
      rvm1_install_flags: '--auto-dotfiles'
      rvm1_rvm_check_for_updates: False
      rvm1_rubies: ['ruby-{{ruby_version}}']
    - role: software/jekyll
      jekyll_ruby_version: '{{ ruby_version }}'
