---
- name: Provision Jumpbox
  hosts: jumpbox
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - { role: software/common/ansible-postfix, tags: ['postfix'] }
    - { role: software/jumpbox }
