---
- hosts: all
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:

        - name: nginx
          path: "/var/log/nginx/*.log"
          options:
            - weekly
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 4
          scripts:
            postrotate: "[ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`"

        - name: apache2
          path: "/var/log/apache2/*.log"
          options:
            - weekly
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 4
          scripts:
            postrotate: "/etc/init.d/apache2 reload > /dev/null"

        - name: audit-log
          path: "/var/log/audit/audit.log"
          options:
            - weekly
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - rotate 4

  tasks:
    # apache2 has it's own config in /etc/logrotate.d/apache2, which we want to override
    - name: remove duplicate apache logrotate config
      file: path=/etc/logrotate.d/apache state=absent

#/var/log/harvester_run.log
#/var/log/fetch-consumer.log
#/var/log/gather-consumer.log
#/var/log/ckan_report.log
#/var/log/ckan_tracking.log
#/var/log/wp-cron.log
