---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/infrastructure/common/vars/main.yml
    - roles/infrastructure/catalog/vars/main.yml

  tasks:
    - include: roles/infrastructure/common/tasks/vpc.yml
    - include: roles/infrastructure/common/tasks/igw.yml
    - include: roles/infrastructure/catalog/tasks/subnets.yml
    - include: roles/infrastructure/catalog/tasks/route_tables.yml
