---
- name: Set the deploy version
  hosts: pycsw-web,pycsw-worker,!v2
  tasks:
    - name: Set deploy version
      set_fact:
        pycsw_deploy_version: "{{ '%Y%m%d%H%M%SZ' | strftime(ansible_date_time.epoch) }}"
      run_once: true
  tags: always

- name: CSW web
  hosts: pycsw-web,!v2
  serial: 1
  roles:
    - role: gsa.datagov-deploy-pycsw
      pycsw_role: web
  tags:
    - pycsw

- name: CSW worker
  hosts: pycsw-worker,!v2
  roles:
    - role: gsa.datagov-deploy-pycsw
      pycsw_role: worker
  tags:
    - pycsw
