---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  - name: Remove OS redis packages
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - "redis-server"
      - "redis-tools"

  - name: Purge redis packages
    apt:
      name: "{{ item }}"
      state: absent
      purge: yes
    with_items:
      - "redis-server"
      - "redis-tools"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'