---
- name: Install CKAN Stack
  hosts: ckan-server
  sudo: yes
  #remote_user: ubuntu

  roles:
    - common
    - apache       
    - postgresql
    - solr
    - ckan-app     
    - ckan-db      
    - ckan-harvest
    - saml2
