---
- name: Install CKAN Stack
  hosts: ckan-server
  sudo: yes
  #remote_user: ubuntu

  roles:
    - roles/app/catalog/common
    - roles/app/catalog/apache       
    - roles/app/catalog/postgresql
    - roles/app/catalog/solr
    - roles/app/catalog/ckan-app     
    - roles/app/catalog/ckan-db      
    - roles/app/catalog/ckan-harvest
    - roles/app/catalog/pycsw
    - roles/app/catalog/saml2
