---
- name: Install CKAN Front End Webserver with no db
  hosts: ckan-frontend-webserver
  remote_user: root

  roles:
    - common
    - saml2
    - apache       
    - solr
    - ckan-app     
    - ckan-config  
