- name: prepare packages needed for solr
  action: apt pkg={{item}} state=installed
  with_items:
    - tomcat6

- name: Download solr 4.2.1
  command: creates=~/solr-4.2.1.tgz chdir=~/ wget -T 40  http://archive.apache.org/dist/lucene/solr/4.2.1/solr-4.2.1.tgz
  when: local_solr == "no" or local_solr == "n"

- name: Copy solr 4.2.1
  action: copy src=cache/solr-4.2.1.tgz dest=~/solr-4.2.1.tgz
  when: local_solr == "yes" or local_solr == "y"

- name: Unpack solr
  shell: "cd ~/ && tar -zxvf solr-4.2.1.tgz && cd solr-4.2.1/dist && cp solr-4.2.1.war /var/lib/tomcat6/webapps/solr.war"

- name: wait for the solr directory to be created
  wait_for: path=/var/lib/tomcat6/webapps/solr/WEB-INF/

- name: Setup solr home folder
  shell: "mkdir -p /home/solr && cp -R ~/solr-4.2.1/example/solr/* /home/solr && mv /home/solr/collection1 /home/solr/ckan"

- name: Change default solr collection1 to ckan
  replace: dest=/home/solr/solr.xml regexp='collection1' replace='ckan'

- name: copy needed solr config file
  action: copy src=web.xml dest=/var/lib/tomcat6/webapps/solr/WEB-INF/web.xml force=yes

- name: copy needed solr config file
  action: copy src=schema.xml dest=/home/solr/ckan/conf/schema.xml force=yes

- name: Setup solr permissions
  shell: "chown -R tomcat6 /home/solr"

- name: restarting tomcat service
  action: service name=tomcat6 state=restarted
