--- # Dashboard repo deployment & composer install

- name: Load inventory specific vault ({{ vars_group }})
  include_vars: "group_vars/{{ vars_group }}/vault.yml"

- name: Load inventory specific variables ({{ vars_group }})
  include_vars: "group_vars/{{ vars_group }}/vars.yml"


- name: Check weather new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: cp -r "{{ project_source_new_code_path }}" "{{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ project_source_path }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Clone project files
  git:
    repo: "{{ project_git_repo }}"
    dest: "{{ project_source_new_code_path }}"
    version: "{{ project_git_version }}"
    force: true

- name: Ensuring config directory exists
  file:
    path: "{{ project_source_new_code_path }}/application/config/{{ codeigniter_environment }}"
    state: directory

- name: Copying config files
  template:
    src: "{{ item }}"
    dest: "{{ project_source_new_code_path }}/application/config/{{ codeigniter_environment }}/{{ item | basename }}"
  with_fileglob:
    - ../templates/config/*.php

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ project_source_path }}"
    state: link

