---

- name: Check if plugins are installed
  command: "td-agent-gem list -i {{item}}"
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}
  with_items: "{{td_agent_plugins}}"
  changed_when: False
  failed_when: False
  register: td_plugin_status

- name: Install missing plugins
  command: "td-agent-gem install {{item.item}}"
  environment:
    PATH: /usr/sbin:{{ ansible_env.PATH }}
  with_items: "{{td_plugin_status.results}}"
  when: (td_plugin_status.results is defined) and
        (item.stdout_lines[0] == "false")

- name: Configure td-agent service
  lineinfile: dest=/etc/init.d/td-agent line="export AWS_REGION=us-east-1" state=present insertafter="export PATH=/sbin:/usr/sbin:/bin:/usr/bin"


# Configure permissions
# need to change the permissions. Hard-coding version here, but if that's a problem
# we can use this relatively simple hack http://stackoverflow.com/questions/22476097/how-to-mention-wildcard-in-ansible-commands
- name: Configure AWS ES plugin gem permissions
  file: path=/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems recurse=true state=directory mode=0775

- name: Configure gemspec permissions
  file: path=/opt/td-agent/embedded/lib/ruby/gems/2.1.0/specifications recurse=true mode=0775

# figure out a more secure way for log file permissions in prod
- name: Configure log permissions
  file: path=/var/log recurse=true state=directory mode=0755

- name: Remove config.d folder
  file: path=/etc/td-agent/config.d state=absent
  notify: restart td-agent

- name: Create config.d folder
  file: path=/etc/td-agent/config.d state=directory

- name: Configure td-agent.conf
  template:
    src: td-agent.j2
    dest: /etc/td-agent/td-agent.conf

- name: Configure system sources
  template:
    src: system-source.j2
    dest: /etc/td-agent/config.d/1-system-source.conf
  tags: system

- name: Configure app sources
  template:
    src: "{{ group_names[0] }}-source.j2"
    dest: /etc/td-agent/config.d/1-{{ group_names[0] }}-source.conf
  tags: app

- name: Configure host filters
  template:
    src: host-filter.j2
    dest: /etc/td-agent/config.d/2-host-filter.conf
  tags: filters

- name: Configure ElasticSearch matcher
  template:
    src: elasticsearch-match.j2
    dest: /etc/td-agent/config.d/3-elasticsearch-match.conf
  tags: elasticsearch

- name: Configure BSP matcher
  template:
    src: bsp-match.j2
    dest: /etc/td-agent/config.d/4-bsp-match.conf
  tags: bsp

- name: Configure debug  matcher
  template:
    src: debug-match.j2
    dest: /etc/td-agent/config.d/5-debug-match.conf
  tags: debug
