---
#- name: treasuredata apt key
#  apt_key: url=https://packages.treasuredata.com/GPG-KEY-td-agent state=present validate_certs=no

#- name: apt repo
#  apt_repository: repo='deb http://packages.treasuredata.com/2/ubuntu/precise/ precise contrib' state=present
- name: install rbenv dependencies
  apt: name={{item}} state=installed
  become: true
  with_items: 
       - git
       - curl
       - zlib1g-dev
       - build-essential
       - libssl-dev
       - libreadline-dev
       - libyaml-dev
       - libsqlite3-dev
       - sqlite3
       - libxml2-dev
       - libxslt1-dev
       - libcurl4-openssl-dev
       - python-software-properties
       - libffi-dev

- name: install rbenv1
  command: cd /home/ubuntu
- name: install rbenv2
  command: git clone git://github.com/sstephenson/rbenv.git .rbenv
- name: install rbenv3
  command: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
- name: install rbenv4
  command: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
- name: install rbenv3
  command: git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
- name: install rbenv3
  command: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_profile
- name: install rbenv3
  command: source ~/.bash_profile

- name: install td-agent
  apt: name=td-agent state=latest force=yes

#- name: install td-agent
#  command: "curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-precise-td-agent2.sh | sh"

- name: service td-agent
  service: name=td-agent state=started enabled=yes

- name: Check plugins
  command: "td-agent-gem list --local {{ item.name }}"
  with_items: "{{ td_agent.plugins }}"
  changed_when: False
  failed_when: False
  register: plugin_status

- name: Install plugins
  command: "td-agent-gem install {{ item.item.name }}"
  with_items: plugin_status.results
  when: plugin_status.results is defined and item.stdout[0] is undefined

- name: td-agent template copy
  template: >
    src=td-agent.conf
    dest=/etc/td-agent/td-agent.conf
    backup=yes
  notify: restart td-agent

- name: create temp directory use posision
  file: >
    path={{ td_agent.position_path }}
    state=directory
    owner=td-agent
    group=td-agent
    mode=755
