---
- name: Adding Bedrock .env to {{ php_app_deployment_dir }}/src/.env
  template:
    src: ".env"
    dest: "{{ php_app_deployment_dir }}/src/.env"

- name: Copy W3 Total Cache files
  template:
    src: "w3tc-wp-loader.php"
    dest: "{{ php_app_deployment_dir }}/src/web/app/plugins/w3tc-wp-loader.php"

- name: Making sure saml config directory exists
  file:
    dest: "{{ php_app_deployment_dir }}/src/web/app/uploads/saml-20-single-sign-on/etc/config"
    state: directory
    recurse: yes

- name: Copy saml20-idp-remote ini
  template:
    src: "saml20-idp-remote.ini"
    dest: "{{ php_app_deployment_dir }}/src/web/app/uploads/saml-20-single-sign-on/etc/config/saml20-idp-remote.ini"

- name: Making sure saml config directory exists
  file:
    dest: "{{ php_app_deployment_dir }}/src/web/app/uploads/saml-20-single-sign-on/etc/certs/1"
    state: directory
    recurse: yes

- name: Copy SAML crt
  template:
    src: "mycert.pem"
    dest: "{{ php_app_deployment_dir }}/src/web/app/uploads/saml-20-single-sign-on/etc/certs/1/1.cer"
    mode: 0644

- name: Copy SAML key
  template:
    src: "mykey.pem"
    dest: "{{ php_app_deployment_dir }}/src/web/app/uploads/saml-20-single-sign-on/etc/certs/1/1.key"
    mode: 0644

- name: Copy saml_authentication_options json
  template:
    src: "saml.json"
    dest: "{{ php_app_deployment_dir }}/src/saml.json"

- name: Copy saml-20-single-sign-on config
  template:
    src: "saml-config.php"
    dest: "{{ php_app_deployment_dir }}/src/web/app/plugins/saml-20-single-sign-on/saml/config/config.php"

- name: Copy s3 tantan_wordpress_s3 config json
  template:
    src: "s3.json"
    dest: "{{ php_app_deployment_dir }}/src/s3.json"

- name: Disabling saml on local
  command: wp plugin deactivate saml-20-single-sign-on
  args:
    chdir: "{{ php_app_deployment_dir }}/src"
  when: "'development' == web_app_env"
  run_once: true
  tags: wp-cli

- name: update s3 options
  shell: wp option update tantan_wordpress_s3 --format=json < s3.json
  args:
    chdir: "{{ php_app_deployment_dir }}/src"
  run_once: true
  tags:
    - skip_ansible_lint
    - wp-cli

- name: Update saml saml_authentication_options
  shell: wp option update saml_authentication_options --format=json < saml.json
  args:
    chdir: "{{ php_app_deployment_dir }}/src"
  run_once: true
  tags:
    - skip_ansible_lint
    - wp-cli

- name: Updating admin pass if env=Dev
  command: wp user update admin --user_pass=password
  args:
    chdir: "{{ php_app_deployment_dir }}/src"
  when: "'development' == web_app_env"
  run_once: true
  tags:
    - wp-cli

- name: Enabling dev plugins if env=Dev
  command: wp plugin activate check-email debug-bar log-deprecated-notices query-monitor
  args:
    chdir: "{{ php_app_deployment_dir }}/src"
  when: "'development' == web_app_env"
  run_once: true
  tags:
    - wp-cli

- name: Remove vulnerable swfupload.swf
  file:
    dest: "{{ php_app_deployment_dir }}/src/web/wp/wp-includes/js/swfupload/swfupload.swf"
    state: absent

- name: Remove a line in amazon-s3-and-cloudfront plugin to fix url issues
  lineinfile:
    path: "{{ php_app_deployment_dir }}/src/web/app/plugins/amazon-s3-and-cloudfront/classes/as3cf-filter.php"
    regexp: '\$value.*\$this->replace_urls\( \$value, \$url_pairs \);'
    state: absent

# - name: Set up main wp cronjob
#  cron:
#    name: "Set up main wp cronjob"
#    minute: "*/10"
#    job: "/usr/bin/php {{ current_source_symlink }}/web/wp/wp-cron.php >> /var/log/wp-cron.log 2>&1" #todo: Use SES to send this to a recipient list
#  run_once: true
