---
- name: Mkdir /var/www/
  file:
    path: "/var/www"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Mkdir /var/www/datagov
  file:
    path: "/var/www/datagov"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0777

- name: Setup Datagov WP system cron
  cron:
    name: "Data.gov WordPress cron"
    minute: "*/15"
    user: "www-data"
    job: "cd {{ current_source_symlink }} && wp cron event run --due-now >> /var/log/wp-cron.log 2>&1"
    cron_file: "wordpress-datagov"
  when: crons_enabled

- name: Installing required trusty packages
  apt:
    name:
      - mariadb-client-5.5
      - mariadb-client
      - php-zip
      - nginx-extras
    state: present
    force: yes
  when: ansible_distribution_release == "trusty"

- name: Installing required bionic packages
  apt:
    name:
      - mariadb-client-10.1
      - mariadb-client
      - php-zip
      - nginx-extras
    state: present
    force: yes
  when: ansible_distribution_release == "bionic"

- name: Import nginx extra modules
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'include /etc/nginx/modules-enabled/*.conf;'
    create: yes
    insertbefore: BOF

- name: Copying Data.gov configuration for Nginx
  template:
    src: "datagov.nginx.conf"
    dest: "/etc/nginx/sites-enabled/datagov.nginx.conf"
  notify:
    - reload nginx
