---
- name: uninstall pip provided supervisor
  pip: name=supervisor state=absent

- name: remove old pip supervisor files
  file: path={{ item }} state=absent
  with_items:
    - /etc/supervisord.conf
    - /var/log/supervisord.log

- name: install supervisor
  apt: name=supervisor state=present

- name: copy template files
  template:
    src: etc/supervisor/conf.d/jekyll.conf.j2
    dest: /etc/supervisor/conf.d/jekyll.conf
    mode: 0640
  notify:
    - restart supervisord

- name: ensure supervisor is enabled
  service:
    name: supervisor
    state: started
    enabled: yes

- name: ensure jekyll services are started
  supervisorctl: name=jekyll-{{ item.name }} state=started
  with_items: "{{ jekyll_apps }}"
  tags:
    # https://github.com/ansible/ansible/issues/3977 fixed in ansible 2.7.5
    - skip_in_kitchen
