---
- name: install supervisor
  action: pip name=supervisor

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/init/supervisor.conf

- name: copy template files
  template: src=templates/{{item}}.j2 dest=/{{item}}
  with_items:
    - etc/supervisord.conf

- name: update supervisor if necessary
  shell: supervisorctl reread && supervisorctl update
  ignore_errors: yes

- name: start supervisor
  service: name=supervisor state=restarted
