---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ckan-native-login
    image: ubuntu:trusty
    groups:
      - catalog-web
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../../..
  inventory:
    group_vars:
      catalog-web:
        app_type: catalog
        catalog_bucket_name: s3bucket
        catalog_ckan_redis_host: localhost
        catalog_ckan_solr_host: localhost
        catalog_db_user: ckan
        catalog_db_name: ckan
        catalog_db_pass: ckandbpassword
        ckan_instance_secret: ckansecret
        ckan_instance_uuid: ckanuuid
        ckan_site_domain: https://ckan.example.com
        pycsw_db_server: localhost
        redis_pass: redispassword
        who_ini_secret: whosecret
        who_secure: false
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
