---

# Setup the machine similar to if we ran the catalog playbook.
- name: Prepare
  hosts: all
  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - apache2
        - git
        - libbz2-dev
        - libpq-dev
        - libxml2-dev
        - libxslt1-dev
        - python-dev
        - python-virtualenv
        - swig
        - xmlsec1

    - name: setup ckan virtualenv
      pip:
        name: pip
        version: "8.1.1"
        virtualenv: /usr/lib/ckan

    - name: create ckan config directory
      file:
        dest: /etc/ckan
        state: directory
        mode: 0755
