# provide some default values to be overwritten later by group vars and host vars...
jekyll_apps:
      - {
          name: "sdg-indicators",
          repo: "https://github.com/GSA/sdg-indicators/",
          config: "_config_prod.yml",
          branch: "master",
          port: 8000,
          s3_bucket: "{{ s3_bucket_sdg | default('')}}",
          secret_key: "{{ jekyll_webhook_secret | default('')}}"
        }
      - {
          name: "data-federation",
          repo: "https://github.com/GSA/us-data-federation",
          config: "_config_prod.yml",
          branch: "master",
          port: 8001,
          s3_bucket: "{{ s3_bucket_federation | default('')}}",
          secret_key: "{{ jekyll_webhook_secret | default('')}}"
        }