# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

- name: Restart php7.0-fpm
  shell: /etc/init.d/php7.0-fpm restart

- name: Restart nginx
  service: name=nginx state=restarted