# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

- name: php7.0-fpm status
  shell: /etc/init.d/php7.0-fpm status
  register: php_fpm_status

- name: Start php7.0-fpm
  shell: /etc/init.d/php7.0-fpm start
  when: '"is not running" in php_fpm_status.stdout'

- name: ReStart php7.0-fpm
  shell: /etc/init.d/php7.0-fpm restart
  when: '"is running" in php_fpm_status.stdout'

- name: Restart nginx
  service: name=nginx state=restarted