# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes

- name: Chown www-data /var/www/
  file:
    path: "/var/www"
    owner: "ubuntu"
    group: "www-data"
    recurse: yes

- name: Reload php7.0-fpm
  service: name=php7.0-fpm state=reloaded

- name: Reload nginx
  service: name=nginx state=reloaded