---
- name: Clone CKAN app
  action: git repo={{ app_repo }} dest={{ app_source_path }} 

# Remove virtualenv
- name: Remove CKAN virtualenv
  shell: rm -rf {{ virtual_env }} 

- name: Install CKAN app
  pip: requirements={{ app_source_path }}/requirements.txt virtualenv={{ virtual_env }} virtualenv_site_packages=yes

# CKAN Core installation
- name: Install CKAN Core
  pip: requirements={{ virtual_env }}/src/ckan/requirements.txt virtualenv={{ virtual_env }}

# CKAN Extensions installation
- name: Install ckanext-harvest
  pip: requirements={{ virtual_env }}/src/ckanext-harvest/pip-requirements.txt virtualenv={{ virtual_env }}

- name: Install ckanext-spatial
  pip: requirements={{ virtual_env }}/src/ckanext-spatial/pip-requirements.txt virtualenv={{ virtual_env }}

#- name: Install ckanext-saml2
#  pip: requirements={{ virtual_env }}/src/ckanext-saml2/requirements.txt virtualenv={{ virtual_env }}

# Configure CKAN
- name: Configure CKAN App
  shell: cp -r {{ app_source_path }}/config/environments/{{ env }}/* /etc/ckan
