---

# Web Proxy
web_proxy_ami_id: ami-d566f7c2
web_proxy_instance_size: t2.micro
nginx_config_path: /etc/nginx/sites-available/default.conf
assign_public_ip: yes

# Web
web_ami_id: ami-60019377 #ami-d566f7c2 
web_instance_size: t2.medium

# Harvester
harvester_ami_id: ami-67a13270 #ami-d566f7c2
harvester_instance_size: t2.medium

# Solr
solr_ami_id: ami-b00796a7
solr_instance_size: t2.micro

# Jump Box
jump_box_ami_id: ami-d566f7c2
jump_box_instance_size: t2.micro

# Other
key_name: ckan-csw-aws
