---

subnets:
  public_subnet_1:
    cidr: 172.22.0.0/24 
    az: us-east-1b
    type: public
  public_subnet_2:
    cidr: 172.22.1.0/24
    az: us-east-1c
    type: public
  private_subnet_1:
    cidr: 172.22.2.0/24
    az: us-east-1b
    type: private
  private_subnet_2:
    cidr: 172.22.3.0/24
    az: us-east-1c
    type: private
  db_private_subnet_1:
    cidr: 172.22.4.0/24
    az: us-east-1b
    type: db-private
  db_private_subnet_2:
    cidr: 172.22.5.0/24
    az: us-east-1c
    type: db-private
